# Generated by Django 6.1 on 2026-09-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='Files/%Y/%m/', verbose_name='Archivo')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
        ),
    ]
