# Generated by Django 6.1 on 2026-09-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(upload_to='Files/%Y/', verbose_name='Archivo'),
        ),
    ]
