# Generated by Django 5.2.17 on 2026-10-05 02:48

import apps.landing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_contactattachment_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactattachment',
            name='file',
            field=models.FileField(upload_to=apps.landing.validators.private_path),
        ),
    ]
