# Generated by Django 5.2.17 on 2026-10-05 03:18

from django.db import migrations, models


def retain_catalog(apps, schema_editor):
    apps.get_model('landing','Product').objects.filter(is_active=True).update(is_public=True)

class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_contactattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Mostrar en la página web'),
        ),
        migrations.RunPython(retain_catalog, migrations.RunPython.noop),
    ]
