# Generated by Django 5.2.17 on 2026-10-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_product_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('customer', 'Cliente'), ('admin', 'VillaTech')], max_length=10)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Aceptado por proveedor'), ('failed', 'Falló')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=160)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='landing.contact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contact', 'audience'), name='unique_contact_email_audience')],
            },
        ),
    ]
