# Generated by Django 5.2.18 on 2026-10-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=25, verbose_name='Teléfono'),
        ),
    ]
