# Generated by Django 5.2.18 on 2026-10-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_alter_contact_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
