# Generated by Django 5.2.18 on 2026-10-10 04:21

import apps.landing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_contactattachment_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_model',
            field=models.FileField(blank=True, upload_to=apps.landing.validators.private_path, validators=[apps.landing.validators.validate_print_model], verbose_name='Modelo de impresión'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_model_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
