# Generated by Django 5.2.17 on 2026-10-05 02:48

import apps.landing.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'Venta'), ('order', 'Pedido'), ('expense', 'Gasto')], max_length=10, verbose_name='Tipo')),
                ('title', models.CharField(max_length=150, verbose_name='Descripción')),
                ('customer', models.CharField(blank=True, max_length=150, verbose_name='Cliente')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor total COP')),
                ('category', models.CharField(choices=[('filament', 'Compra de filamento'), ('monthly', 'Pago mensual'), ('maintenance', 'Mantenimiento'), ('other', 'Otro')], default='other', max_length=15, verbose_name='Categoría de gasto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('printing', 'En impresión'), ('ready', 'Listo'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Estado del pedido')),
                ('filament_g', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Filamento consumido (g)')),
                ('image', models.ImageField(blank=True, upload_to=apps.landing.validators.private_path, validators=[apps.landing.validators.validate_image], verbose_name='Imagen de referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
