# Generated by Django 5.2.17 on 2026-10-05 03:18

import apps.landing.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def printers(apps,schema_editor):
    profile=apps.get_model('management','PrinterProfile')
    for name,watts in [('Creality K1C',350),('Flashforge Creator 5 Pro',1200)]:
        profile.objects.get_or_create(name=name,defaults={'rated_watts':watts})

class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_product_is_public'),
        ('management', '0002_entry_acquired_filament_g_entry_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Impresora')),
                ('rated_watts', models.PositiveIntegerField(blank=True, null=True, verbose_name='Potencia nominal (W)')),
                ('average_watts', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potencia media medida (W)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de adquisición COP')),
                ('useful_hours', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vida útil estimada (h)')),
                ('maintenance_hour', models.DecimalField(decimal_places=2, default=200, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reserva mantenimiento COP/h')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='logo_theme',
            field=models.CharField(choices=[('light', 'Blanco'), ('dark', 'Negro')], default='light', max_length=5, verbose_name='Logo del PDF'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Producto / descripción')),
                ('length_cm', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Largo cm')),
                ('width_cm', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho cm')),
                ('height_cm', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto cm')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario COP')),
                ('image', models.ImageField(blank=True, upload_to=apps.landing.validators.private_path, validators=[apps.landing.validators.validate_image], verbose_name='Imagen del producto')),
                ('comparison_image', models.ImageField(blank=True, upload_to=apps.landing.validators.private_path, validators=[apps.landing.validators.validate_image], verbose_name='Imagen de comparación / escala')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.entry')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.productvariant')),
            ],
        ),
        migrations.RunPython(printers, migrations.RunPython.noop),
    ]
