# Generated by Django 5.2.17 on 2026-10-05 10:11

import apps.landing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_printerprofile_entry_logo_theme_quoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='quotation_pdf',
            field=models.FileField(blank=True, editable=False, upload_to=apps.landing.validators.private_path),
        ),
    ]
