# Generated by Django 5.2.17 on 2026-10-05 15:14

import apps.landing.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_product_is_public'),
        ('management', '0004_entry_quotation_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción del producto / proyecto'),
        ),
        migrations.AddField(
            model_name='entry',
            name='print_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas de impresión'),
        ),
        migrations.AddField(
            model_name='entry',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landing.categoryproduct', verbose_name='Categoría de producto'),
        ),
        migrations.AddField(
            model_name='entry',
            name='reference_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.product', verbose_name='Producto de referencia (opcional)'),
        ),
        migrations.AddField(
            model_name='entry',
            name='sold_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de venta'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='kind',
            field=models.CharField(choices=[('quote', 'Cotización'), ('sale', 'Venta'), ('order', 'Pedido'), ('expense', 'Gasto')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('quoted', 'Cotizado'), ('sold', 'Vendido'), ('pending', 'Pendiente'), ('printing', 'En impresión'), ('ready', 'Listo'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Estado del pedido'),
        ),
        migrations.CreateModel(
            name='DevelopmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre del proyecto')),
                ('project_type', models.CharField(choices=[('design', 'Diseño digital / UX'), ('web', 'Desarrollo web'), ('mobile', 'Aplicación móvil'), ('software', 'Software a medida'), ('automation', 'Automatización')], default='software', max_length=15, verbose_name='Tipo de trabajo')),
                ('description', models.TextField(verbose_name='Qué hace el aplicativo / alcance')),
                ('customer', models.CharField(blank=True, max_length=150, verbose_name='Cliente')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('active', 'En desarrollo'), ('paused', 'En pausa'), ('delivered', 'Finalizado')], default='active', max_length=15, verbose_name='Estado')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.landing.validators.private_path, validators=[apps.landing.validators.validate_image], verbose_name='Captura del aplicativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='management.developmentproject')),
            ],
        ),
    ]
