# Generated by Django 5.2.17 on 2026-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_initial_categories_sold_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('filament', 'Compra de filamento'), ('monthly', 'Pago mensual'), ('maintenance', 'Mantenimiento'), ('energy', 'Energía'), ('software', 'Software y licencias'), ('supplies', 'Insumos'), ('services', 'Servicios'), ('other', 'Otro')], default='other', max_length=15, verbose_name='Categoría de gasto'),
        ),
    ]
