# Generated by Django 5.2.17 on 2026-10-06 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_contactemail'),
        ('management', '0007_alter_entry_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='landing.contact'),
        ),
        migrations.AddField(
            model_name='entry',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del cliente'),
        ),
        migrations.AddField(
            model_name='entry',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Teléfono del cliente'),
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.CharField(choices=[('manual', 'Gestión'), ('web', 'Página web')], default='manual', max_length=10, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('quoted', 'Cotizado'), ('sold', 'Vendido'), ('pending', 'Pendiente'), ('printing', 'En impresión'), ('ready', 'Listo'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Estado del pedido'),
        ),
    ]
