# Generated by Django 5.2.18 on 2026-10-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Confirmado el'),
        ),
        migrations.AddField(
            model_name='entry',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entrega estimada'),
        ),
        migrations.CreateModel(
            name='OperationalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Falló')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='management.entry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
