# Generated by Django 5.2.18 on 2026-10-09 15:07

import apps.landing.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_entry_approved_at_entry_estimated_delivery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='approval_channel',
            field=models.CharField(blank=True, choices=[('email', 'Enlace del correo'), ('message', 'Mensaje'), ('internal', 'Gestión')], max_length=10, verbose_name='Medio de confirmación'),
        ),
        migrations.AddField(
            model_name='entry',
            name='approval_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='approval_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Referencia de confirmación'),
        ),
        migrations.AddField(
            model_name='entry',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades'),
        ),
        migrations.AddField(
            model_name='entry',
            name='quote_expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='quote_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='unit_filament_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Filamento por unidad g'),
        ),
        migrations.AddField(
            model_name='entry',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario COP'),
        ),
        migrations.AddField(
            model_name='entry',
            name='unit_print_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas por unidad'),
        ),
        migrations.AddField(
            model_name='operationalemail',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.landing.validators.private_path),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción y acabado'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='unit_filament_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Filamento por unidad g'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='unit_print_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas por unidad'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('quoted', 'Preparada'), ('sent', 'Enviada'), ('expired', 'Vencida'), ('sold', 'Vendido'), ('pending', 'Pendiente'), ('printing', 'En impresión'), ('ready', 'Listo'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='operationalemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Falló'), ('skipped', 'Descartado')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='EntryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='management.entry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
