# Generated by Django 5.2.18 on 2026-10-09 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_initialize_unit_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='delivery_settled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo liquidado al entregar COP'),
        ),
        migrations.AlterField(
            model_name='operationalemail',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='management.entry'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.entry'),
        ),
        migrations.CreateModel(
            name='CustomerIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo para responder')),
                ('comment', models.TextField(max_length=2000, verbose_name='¿Qué ocurrió?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_issues', to='management.entry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
